#!/bin/bash

VERSION_BRANCH=${TENDERMINT_VERSION:-v0.34.0}
TENDERMINT_REPO_URL=https://raw.githubusercontent.com/tendermint/tendermint/${VERSION_BRANCH}
TENDERMINT_REPO_PROTO_PATH=proto

GRPC_DIR=src/main/scala/com/bidzyyys/signchain/grpc
PROTOBUF_DIR=src/main/protobuf

TM_ABCI_DIR=tendermint/abci

TM_ABCI_FILE_PATH=${TM_ABCI_DIR}/types.proto
TM_ABCI_LOCAL_FILE_PATH=${PROTOBUF_DIR}/${TM_ABCI_FILE_PATH}

TM_CRYPTO_DIR=tendermint/crypto

TM_PROOF_FILE_PATH=${TM_CRYPTO_DIR}/proof.proto
TM_PROOF_LOCAL_FILE_PATH=${PROTOBUF_DIR}/${TM_PROOF_FILE_PATH}

TM_KEYS_FILE_PATH=${TM_CRYPTO_DIR}/keys.proto
TM_KEYS_LOCAL_FILE_PATH=${PROTOBUF_DIR}/${TM_KEYS_FILE_PATH}

TM_TYPES_DIR=tendermint/types

TM_PARAMS_FILE_PATH=${TM_TYPES_DIR}/params.proto
TM_PARAMS_LOCAL_FILE_PATH=${PROTOBUF_DIR}/${TM_PARAMS_FILE_PATH}

TM_TYPES_FILE_PATH=${TM_TYPES_DIR}/types.proto
TM_TYPES_LOCAL_FILE_PATH=${PROTOBUF_DIR}/${TM_TYPES_FILE_PATH}

TM_VALIDATOR_FILE_PATH=${TM_TYPES_DIR}/validator.proto
TM_VALIDATOR_LOCAL_FILE_PATH=${PROTOBUF_DIR}/${TM_VALIDATOR_FILE_PATH}

TM_VERSION_DIR=tendermint/version
TM_VERSION_FILE_PATH=${TM_VERSION_DIR}/types.proto
TM_VERSION_LOCAL_FILE_PATH=${PROTOBUF_DIR}/${TM_VERSION_FILE_PATH}

THIRD_PARTY_DIR=third_party/proto/gogoproto
THIRD_PARTY_FILE=${THIRD_PARTY_DIR}/gogo.proto
THIRD_PARTY_LOCAL_DIR=${PROTOBUF_DIR}/gogoproto
THIRD_PARTY_LOCAL_FILE_PATH=${THIRD_PARTY_LOCAL_DIR}/gogo.proto

update_proto() {
    rm -rf ${PROTOBUF_DIR}

    mkdir -p ${THIRD_PARTY_LOCAL_DIR}

    mkdir -p ${PROTOBUF_DIR}/${TM_ABCI_DIR}
    mkdir -p ${PROTOBUF_DIR}/${TM_CRYPTO_DIR}
    mkdir -p ${PROTOBUF_DIR}/${TM_TYPES_DIR}
    mkdir -p ${PROTOBUF_DIR}/${TM_VERSION_DIR}

    echo Downloading protobuf files

    curl -s ${TENDERMINT_REPO_URL}/${THIRD_PARTY_FILE} >${THIRD_PARTY_LOCAL_FILE_PATH}

    curl -s ${TENDERMINT_REPO_URL}/${TENDERMINT_REPO_PROTO_PATH}/${TM_ABCI_FILE_PATH} >${TM_ABCI_LOCAL_FILE_PATH}
    curl -s ${TENDERMINT_REPO_URL}/${TENDERMINT_REPO_PROTO_PATH}/${TM_KEYS_FILE_PATH} >${TM_KEYS_LOCAL_FILE_PATH}
    curl -s ${TENDERMINT_REPO_URL}/${TENDERMINT_REPO_PROTO_PATH}/${TM_PROOF_FILE_PATH} >${TM_PROOF_LOCAL_FILE_PATH}
    curl -s ${TENDERMINT_REPO_URL}/${TENDERMINT_REPO_PROTO_PATH}/${TM_PARAMS_FILE_PATH} >${TM_PARAMS_LOCAL_FILE_PATH}
    curl -s ${TENDERMINT_REPO_URL}/${TENDERMINT_REPO_PROTO_PATH}/${TM_TYPES_FILE_PATH} >${TM_TYPES_LOCAL_FILE_PATH}
    curl -s ${TENDERMINT_REPO_URL}/${TENDERMINT_REPO_PROTO_PATH}/${TM_VALIDATOR_FILE_PATH} >${TM_VALIDATOR_LOCAL_FILE_PATH}
    curl -s ${TENDERMINT_REPO_URL}/${TENDERMINT_REPO_PROTO_PATH}/${TM_VERSION_FILE_PATH} >${TM_VERSION_LOCAL_FILE_PATH}
}

update_proto
